Working refresh flow
jebrosen/rocket_oauth2 pull request #7
Opened 2019-10-04 16:22 UTC by hcrohland

Here is a working version of a refresh flow.

You can access the managed OAuth and call fn refresh on it.

2019-10-05 16:09 UTC, jebrosen requested changes
So, this is actually a breaking change after all. I'll probably release it at the same time as some ergonomics changes that should make it easier to access instances of `OAuth` or whatever struct will provide `get_redirect` and `refresh`.

2019-10-05 16:09 UTC, jebrosen commented on src/core.rs
> +pub enum Token {
Can we rename this to `TokenRequest`?

Let's also derive `Clone` and `PartialEq`.

2019-10-05 16:09 UTC, jebrosen commented on src/core.rs
> +    fn exchange_code(&self, config: &OAuthConfig, token: Token)
This is a breaking change. I think adding this in a non-breaking way would not be worth it, though.

2019-10-05 17:40 UTC, hcrohland commented on src/core.rs
> +pub enum Token {
Done

2019-10-12 15:58 UTC, jebrosen commented
Thanks for implementing this! Merged in b7aabc4.

2019-10-12 15:58 UTC, closed without merging